[package]
name = "elo_calculator"
version = "0.1.0"
edition = "2021"

[lib]
name = "elo_calculator"
crate-type = ["cdylib"]

[dependencies]
elo-calculator = { path = "../lib" }
pyo3 = { version = "0.18", features = ["extension-module"] }